language: php
php:
  - '7.0'
  - 'hhvm'
  - 'nightly'

before_script:
    - composer install
    - ./vendor/bin/phpcbf ./app/ --no-patch

script:
    - phpunit
    - ./vendor/bin/phpcs --standard=PSR2 app